# -*- coding: utf-8 -*-
"""Nuevo_Rscorer_Tcontinuo_XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yPm6mewLtLyDgURIYzvrHPmaU0Hm2Y-
"""

#CORRE EN   v6e-1 TPU

#!pip install econml

#!pip install dowhy

#!pip install xgboost

import random
import os
import warnings
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV
from econml.dr import SparseLinearDRLearner, ForestDRLearner, LinearDRLearner
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import expon
import scipy.stats as stats
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
import statsmodels.api as sm
from dowhy import CausalModel
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor, XGBClassifier
from dowhy.causal_estimator import CausalEstimate
from sklearn.preprocessing import StandardScaler
from econml.dr import DRLearner
from sklearn.linear_model import LassoCV
from econml.dml import DML, SparseLinearDML

from sklearn.ensemble import (
    HistGradientBoostingRegressor,
    HistGradientBoostingClassifier
)



# Set seeds for reproducibility
def seed_everything(seed=123):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    #os.environ['TF_DETERMINISTIC_OPS'] = '1'

seed = 123
seed_everything(seed)
warnings.filterwarnings('ignore')

#import data
# Montar Google Drive
#from google.colab import drive
#drive.mount('/content/drive')

# Cargar el archivo CSV desde tu Drive
import pandas as pd

# Ruta al archivo en Google Drive
file_path = 'D:/clases/UDES/fortalecimiento institucional/macroproyecto_2025/leish/ci/data_final_15_sep.csv'
data_all = pd.read_csv(file_path, encoding='latin-1')

data_all = data_all.dropna()

columnas_to_drop = ['Year', 'Altitude', 'Forest', 'cases', 'total_pop', 
                      'expected']

# 1. Label Encoding DANE
le = LabelEncoder()
data_all['DANE_labeled'] = le.fit_transform(data_all['DANE'])
scaler = MinMaxScaler()
data_all['DANE_normalized'] = scaler.fit_transform(
    data_all[['DANE_labeled']])

# 2. Label Encoding DANE_Year
le_year = LabelEncoder()
data_all['DANE_Year_labeled'] = le_year.fit_transform(data_all['DANE_year'])
scaler_DDANE = MinMaxScaler()
data_all['DANE_Year_normalized'] = scaler_DDANE.fit_transform(
    data_all[['DANE_Year_labeled']])


data_all.drop(columns=columnas_to_drop, inplace=True)

std_deforestation = data_all['Deforestation_t'].std()
print(f"std of Deforestation_t: {std_deforestation}")

median_Deforestation_t = data_all['Deforestation_t'].median()
print(f"median of Deforestation_t: {median_Deforestation_t}")



# Estandarización de variables continuas
scaler = StandardScaler()
data_all['MPI'] = scaler.fit_transform(data_all[['MPI']])
#data_all['Forest_tm1'] = scaler.fit_transform(data_all[['Forest_tm1']])
data_all['HFP_t'] = scaler.fit_transform(data_all[['HFP_t']])
data_all['Illegal_mining_t'] = scaler.fit_transform(data_all[['Illegal_mining_t']])
data_all['Soil_Moisture'] = scaler.fit_transform(data_all[['Soil_Moisture']])
data_all['Temperature'] = scaler.fit_transform(data_all[['Temperature']])
data_all['Precipitation'] = scaler.fit_transform(data_all[['Precipitation']])
data_all['Vectors'] = scaler.fit_transform(data_all[['Vectors']])
data_all['Fire_t'] = scaler.fit_transform(data_all[['Fire_t']])
data_all['Coca_t'] = scaler.fit_transform(data_all[['Coca_t']])
data_all['Deforestation_t'] = scaler.fit_transform(data_all[['Deforestation_t']])

# std
data_std = data_all[['DANE_normalized', 'DANE_Year_normalized',
                      'MPI', 'Forest_tm1', 'HFP_t', 'Illegal_mining_t', 'Soil_Moisture',
                      'Temperature', 'Precipitation', 'Vectors', 'Fire_t',
                      'Coca_t', 'Deforestation_t', 'excess_tp1']]

# Asegurar orden temporal correcto
data_std = data_std.sort_values(
    by=['DANE_normalized', 'DANE_Year_normalized']
).reset_index(drop=True)


model_deforestation = CausalModel(
    data=data_std,
    treatment=['Deforestation_t'],
    outcome=['excess_tp1'],   
   
    graph="""graph[directed 1 

                node[id "Forest_tm1" label "Forest_tm1"]
                node[id "Precipitation" label "Precipitation"]
                node[id "Temperature" label "Temperature"]
                node[id "Soil_Moisture" label "Soil_Moisture"]
                node[id "MPI" label "MPI"]
                node[id "HFP_t" label "HFP_t"]
                node[id "Coca_t" label "Coca_t"]
                node[id "Fire_t" label "Fire_t"]
                node[id "Illegal_mining_t" label "Illegal_mining_t"]
                node[id "Vectors" label "Vectors"]
                node[id "Deforestation_t" label "Deforestation_t"]
                node[id "excess_tp1" label "excess_tp1"]
                node[id "DANE_normalized" label "DANE_normalized"]
                node[id "DANE_Year_normalized" label "DANE_Year_normalized"]
                

                edge[source "Forest_tm1" target "Precipitation"]
                edge[source "Forest_tm1" target "Temperature"]
                edge[source "Forest_tm1" target "Soil_Moisture"]
                edge[source "Forest_tm1" target "MPI"]
                edge[source "Forest_tm1" target "HFP_t"]
                edge[source "Forest_tm1" target "Coca_t"]
                edge[source "Forest_tm1" target "Fire_t"]
                edge[source "Forest_tm1" target "Illegal_mining_t"]
                edge[source "Forest_tm1" target "Vectors"]
                edge[source "Forest_tm1" target "Deforestation_t"]
                edge[source "Forest_tm1" target "excess_tp1"]

                edge[source "Precipitation" target "Temperature"]
                edge[source "Precipitation" target "Soil_Moisture"]
                edge[source "Precipitation" target "Vectors"]
                edge[source "Precipitation" target "MPI"]
                edge[source "Precipitation" target "HFP_t"]
                edge[source "Precipitation" target "Illegal_mining_t"]
                edge[source "Precipitation" target "excess_tp1"]
                
                edge[source "Temperature" target "Vectors"]
                edge[source "Temperature" target "MPI"]
                edge[source "Temperature" target "HFP_t"]
                edge[source "Temperature" target "Coca_t"]
                edge[source "Temperature" target "Fire_t"]
                edge[source "Temperature" target "Illegal_mining_t"]
                edge[source "Temperature" target "Deforestation_t"]
                edge[source "Temperature" target "excess_tp1"]
                
                edge[source "Soil_Moisture" target "Vectors"]
                edge[source "Soil_Moisture" target "MPI"]
                edge[source "Soil_Moisture" target "HFP_t"]
                edge[source "Soil_Moisture" target "excess_tp1"]
                
                edge[source "MPI" target "HFP_t"]
                edge[source "MPI" target "Coca_t"]
                edge[source "MPI" target "Illegal_mining_t"]
                edge[source "MPI" target "Vectors"]
                edge[source "MPI" target "Deforestation_t"]
                edge[source "MPI" target "excess_tp1"]
                
                edge[source "HFP_t" target "Coca_t"]
                edge[source "HFP_t" target "Fire_t"]
                edge[source "HFP_t" target "Illegal_mining_t"]
                edge[source "HFP_t" target "Vectors"]
                edge[source "HFP_t" target "Deforestation_t"]
                edge[source "HFP_t" target "excess_tp1"]
                
                edge[source "Coca_t" target "Deforestation_t"]
                edge[source "Coca_t" target "excess_tp1"]
                
                edge[source "Fire_t" target "Deforestation_t"]
                edge[source "Fire_t" target "excess_tp1"]
                
                edge[source "Illegal_mining_t" target "Deforestation_t"]
                edge[source "Illegal_mining_t" target "excess_tp1"]
                
                edge[source "Vectors" target "excess_tp1"]
                
                edge[source "Deforestation_t" target "excess_tp1"]
                
                edge[source "DANE_normalized" target "excess_tp1"]
                
                
            ]"""
)



# Generar visualización del DAG
model_deforestation.view_model()

# Mostrar la imagen con matplotlib
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("causal_model.png")
plt.figure(figsize=(16, 12))
plt.imshow(img)
plt.axis('off')
plt.title("DAG Deforestación y Leishmaniasis (Modelo Acíclico)", 
          fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()


# Identifying effects
print("\n" + "=" * 70)
print("IDENTIFICACIÓN DEL ESTIMANDO CAUSAL")
print("=" * 70)

identified_estimand_deforest = model_deforestation.identify_effect(proceed_when_unidentifiable=None)
print(identified_estimand_deforest)

from sklearn.base import BaseEstimator, clone
from sklearn.calibration import CalibratedClassifierCV

# ============================================================================
# WRAPPER PARA CLASIFICADORES PROBABILÍSTICOS
# ============================================================================

class ProbClassifierWrapper(BaseEstimator):
    """
    Wrapper para clasificadores sklearn que retorna probabilidades en predict().

    Para outcomes binarios, EconML espera que model_y.predict(X) devuelva
    E[Y|X] como probabilidades continuas, no clases discretas.
    """
    def __init__(self, base_clf=None, calibrate=True, random_state=123):
        if base_clf is None:
            base_clf = HistGradientBoostingClassifier(
                n_estimators=200,
                #n_jobs=1,
                random_state=random_state,
                class_weight='balanced'
            )
        self.base_clf = base_clf
        self.calibrate = calibrate
        self.random_state = random_state
        self._is_fitted = False

    def fit(self, X, y, **kwargs):
        """Ajusta el clasificador base (con o sin calibración)"""
        y = np.asarray(y).ravel()

        if self.calibrate:
            self.model_ = CalibratedClassifierCV(
                estimator=clone(self.base_clf),
                cv=3
            )
            self.model_.fit(X, y)
        else:
            self.model_ = clone(self.base_clf)
            self.model_.fit(X, y)

        self._is_fitted = True
        return self

    def predict(self, X):
        """Retorna probabilidades de clase positiva (P(Y=1|X))"""
        if not self._is_fitted:
            raise ValueError("ProbClassifierWrapper debe ser ajustado antes de predict()")
        return self.model_.predict_proba(X)[:, 1]

    def predict_proba(self, X):
        """Retorna matriz completa de probabilidades"""
        if not self._is_fitted:
            raise ValueError("ProbClassifierWrapper debe ser ajustado antes de predict_proba()")
        return self.model_.predict_proba(X)


# Imports necesarios
from xgboost import XGBRegressor, XGBClassifier
from econml.score import RScorer
import numpy as np

# ProbClassifierWrapper se asume que está definido y disponible en una celda anterior.

# Define los parámetros fijos para XGBoost
xgb_fixed_params = {
    "random_state": 123,
    "learning_rate": 0.05,
    #"reg_lambda": 'l2_regularization',
    #"alpha": 0.001,
}

# Define las configuraciones de modelos a probar
model_configs = [
    {"name": "Modelo 1", "n_estimators": 5, "max_depth": 2},
    {"name": "Modelo 2", "n_estimators": 5, "max_depth": 3},
    {"name": "Modelo 3", "n_estimators": 7, "max_depth": 2},
    {"name": "Modelo 4", "n_estimators": 7, "max_depth": 3},
    {"name": "Modelo 5", "n_estimators": 10, "max_depth": 2},
    {"name": "Modelo 6", "n_estimators": 10, "max_depth": 3},
    {"name": "Modelo 7", "n_estimators": 13, "max_depth": 3},
    {"name": "Modelo 8", "n_estimators": 13, "max_depth": 2},
    {"name": "Modelo 9", "n_estimators": 15, "max_depth": 3},
    {"name": "Modelo 10", "n_estimators": 15, "max_depth": 2} 
]

# Preparar datos (ya existente en la celda)
Y = data_std['excess_tp1'].values.astype(int)
T = data_std['Deforestation_t'].values
X = data_std[['Forest_tm1', 'DANE_normalized']].values
W = data_std[['Coca_t', 'Fire_t', 'Illegal_mining_t', 'MPI', 'Forest_tm1', 'HFP_t', 'Temperature']].values

# Limpieza de NaNs (ya existente en la celda)
mask_ok = (~np.isnan(Y)) & (~np.isnan(T))
for arr in (X, W):
    mask_ok = mask_ok & (~np.isnan(arr).any(axis=1))

if not mask_ok.all():
    idx = np.where(mask_ok)[0]
    Y = Y[idx]
    T = T[idx]
    X = X[idx, :]
    W = W[idx, :]

print(f"Shapes after filtering: Y={Y.shape}, T={T.shape}, X={X.shape}, W={W.shape}")

results_rscore = []

print("\n============================================================")
print("Calculando R-Score para múltiples modelos DML")
print("============================================================")

for config in model_configs:
    model_name = config["name"]
    n_est = config["n_estimators"]
    depth = config["max_depth"]

    print(f"\n--- Evaluando {model_name} (n_estimators={n_est}, max_depth={depth}) ---")

    # 1) Definir los modelos nuisance (XGBoost)
    model_y_nuisance = HistGradientBoostingClassifier(
        max_iter=n_est,
        max_depth=depth,
        **xgb_fixed_params,
        #use_label_encoder=False,
        #eval_metric='logloss'
    )
    # Envolver para la predicción de probabilidades
    model_y_wrapped = ProbClassifierWrapper(base_clf=model_y_nuisance, calibrate=True, random_state=xgb_fixed_params["random_state"])

    model_t_nuisance = HistGradientBoostingRegressor(
        max_iter=n_est,
        max_depth=depth,
        **xgb_fixed_params,
        #n_jobs=1
    )

    # 2) Instanciar y ajustar el modelo causal DML
    dml_model = DML(
        model_y=model_y_wrapped,
        model_t=model_t_nuisance,
        model_final=LassoCV(
            alphas=[0.0001, 0.001, 0.005, 0.05, 0.01, 0.1],
            fit_intercept=False,
            max_iter=50000,
            tol=1e-3,
            cv=3,
            #n_jobs=-1
        ),
        featurizer=PolynomialFeatures(degree=3, include_bias=False),
        discrete_outcome=True,
        discrete_treatment=False,
        cv=3,
        random_state=xgb_fixed_params["random_state"]
    )
    print("Ajustando DML...")
    dml_model.fit(Y=Y, T=T, X=X, W=W)
    print("DML ajustado.")

    # 3) Calcular R-Score utilizando el método .score() del propio dml_model
    # Esto es preferible ya que el dml_model ya está correctamente configurado para discrete_outcome
    print("Calculando R-Score con dml_model.score()...")
    r_score_value = dml_model.score(Y=Y, T=T, X=X, W=W)

    results_rscore.append((model_name, r_score_value))
    print(f"  R-Score para {model_name}: {r_score_value:.6f}")

print("\n============================================================")
print("Resultados Finales del R-Score:")
print("============================================================")
for name, score in results_rscore:
    print(f"  {name}: {score:.6f}")
print("============================================================")